### ISSUE TITLE
Error when creating Home Assistant sensor

### ISSUE THREAD

**Issue by stevecampion23** [BenoitAnastay/paperless-home-assistant-addon#127]
Firstly, thanks for maintaining such a useful add-on.

I've tried following the "info" instructions on how to create a REST sensor for the inbox. I get this error:
`Invalid config for 'rest' from integration 'sensor' at configuration.yaml, line 113: invalid url for dictionary value 'resource', got 'ca5234a0_paperless-ngx/api/documents/'`

This is what I added to the configuration.yaml:
```
sensor:
  - platform: rest
    unique_id: 5dade7bc-ddb7-442e-bb17-0d379dbf01fb
    resource: ca5234a0_paperless-ngx/api/documents/
    headers:
      Authorization: !secret paperless_auth_header
    params:
      query: "tag:inbox"
    value_template: "{{ value_json.count | int }}"
    name: "Paperless Inbox"
    icon: mdi:inbox
```

I've enabled direct access on port 8000. 

I suspect I need to do something different with the "resource" value, but I'm not sure what. Can you please help?

Thanks!

**Comment by BenoitAnastay** [comment]
There's no need to oppen a port for that purpose, it does use local docker network.

The corrected code should be

```
sensor:
  - platform: rest
    unique_id: 5dade7bc-ddb7-442e-bb17-0d379dbf01fb
    resource: http://ca5234a0-paperless-ngx/api/documents/
    headers:
      Authorization: !secret paperless_auth_header
    params:
      query: "tag:inbox"
    value_template: "{{ value_json.count | int }}"
    name: "Paperless Inbox"
    icon: mdi:inbox
```

The hostname of the add-on differ if you are on edge repository

I'll update the documentation since I put the wrong slug there and forgot the scheme.

**Comment by stevecampion23** [comment]
Thanks for responding to my question so quickly Benoit.
The updated code worked perfectly :-)

**Comment by CR6-SE** [comment]
I have also a Question. 
I did everything described above. And i get no error. But there seems do be no Sensor. 
Where should i find "Paperless Inbox"?

Best Regards

**Comment by BenoitAnastay** [comment]
@CR6-SE it will be in the entities tab

**Comment by CR6-SE** [comment]
Yeah thats the Problem. It isn't there.
And I got no Error to debug.

Maybe a Problem with the Token?

**Comment by CR6-SE** [comment]
There is the Problem:
Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:369
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 11:34:33 (1 Vorkommnisse)
Zuletzt protokolliert: 11:34:33

Platform rest not ready yet: All connection attempts failed; Retrying in background in 30 seconds

Can't find a solution. Do you have any advice?

**Comment by BenoitAnastay** [comment]
If you are on the edge repository the hostname is different, you can check the hostname on the first tab

**Comment by CR6-SE** [comment]
Thx BenoitAnatay,

but i'm a noob :-D I need some more details please. 

Happy easter btw.

**Comment by CR6-SE** [comment]
Okay I cheked my Hostname and it is the same as in the example that you gave. 
The Token I generated in the Adminpanel should be generated with a spezific user?

And is the entry in the secrets.yaml correct?
![image](https://github.com/BenoitAnastay/paperless-home-assistant-addon/assets/75440823/99f9ae55-2fc3-426e-b5eb-858daebea82f)

**Comment by CR6-SE** [comment]
Okay problem still exists.
I generated the token with my user "Arne" should I generate it with consumer or AnonymousUSer?

Thx for your Help!

**Comment by BenoitAnastay** [comment]
Since your account is an administrator account there shouldn't be any restrictions to API usage.

For security best practices it's still better to create a read-only user for API usage.

**Comment by klassm** [comment]
Unfortunately this approach also does not work for me. 

Docker however also shows no exposed port:

```
# docker ps
CONTAINER ID   IMAGE                                                           COMMAND               CREATED         STATUS                 PORTS                                                                                                                                                                                                                                 NAMES
38543e456d18   ghcr.io/benoitanastay/paperless-ngx/aarch64:2.0.4               "/init"               6 hours ago     Up 6 hours                                                                                                                                                                                                                                                   addon_ca5234a0_paperless-ngx
```
Docker inspect also shows no exposed ports.
Anything I have to do to make this work?

Thanks

**Comment by BenoitAnastay** [comment]
If you do use Docker internal hostname you don't need to expose the port, all container can communicate with each others

**Comment by CR6-SE** [comment]
I still can't get that working. Does it may have smth to do with cloudflare?

Best regards.

**Comment by BenoitAnastay** [comment]
@CR6-SE as long as you use internal network it should work even if you cloud flare

**Comment by klassm** [comment]
I also never got it to work, so 🤷‍♂️

Benoit Anastay ***@***.***> schrieb am Mi., 21. Aug. 2024,
20:51:

**Comment by BenoitAnastay** [comment]
Are you all using the hostname displayed in the addon panel ? 
I'll maybe try to replicate this setup to check if everythings work as intended

**Comment by CR6-SE** [comment]
Yes, I do. But it is the same hostname as in your description.

Thx

**Comment by BenoitAnastay** [comment]
So I was able to make my sensor working by changing the request, my configuration is this one.

```
  - platform: rest
    unique_id: 5dade7bc-ddb7-442e-bb17-0d379dbf01fb
    resource: http://44849f5f-paperless-ngx/api/documents/?tags__id=3
    headers:
      Authorization: !secret paperless_auth_header
    value_template: "{{ value_json.count | int }}"
    name: "Paperless Inbox"
    icon: mdi:inbox
```

**Comment by CR6-SE** [comment]
Some Progress. The Sensor is there but not "provided"

![image](https://github.com/user-attachments/assets/af80fc36-d839-4214-95e1-dd11393dff03)

Thx for your Work!

**Comment by BenoitAnastay** [comment]
@CR6-SE you can enable debug on rest api intégration to check what's wrong.

Personally I used tag id instead of tag name, I think it's more reliable, the tag IDs are displayed on top of the edition modal view of tags

**Comment by BenoitAnastay** [comment]
@CR6-SE if you are using stable repository the URL differ from mine 
in your case this configuration should work (replace `?tags__id=3` by the one you need)
```
  - platform: rest
    unique_id: 5dade7bc-ddb7-442e-bb17-0d379dbf01fb
    resource: http://ca5234a0-paperless-ngx/api/documents/?tags__id=3
    headers:
      Authorization: !secret paperless_auth_header
    value_template: "{{ value_json.count | int }}"
    name: "Paperless Inbox"
    icon: mdi:inbox
```
