### ISSUE TITLE
"403 - Forbidden" error when trying to access PG-NGX via an external domain

### ISSUE THREAD

**Issue by csuermann** [BenoitAnastay/paperless-home-assistant-addon#240]
Thank you for the great project!

I'm struggling to access PG-NGX via an external domain using _cloudflared_.

The PG-NGX container shows below log entry, hence the request seems to hit the right endpoint.

`2025/03/14 10:20:06 [error] 1392#1392: *25 access forbidden by rule, client: 172.xx.xx.x, server: 55eca821-paperless-ngx, request: "GET / HTTP/1.1", host: "paperless.mydomain.com"`

Consequently, the browser just displays
<img width="307" alt="Image" src="https://github.com/user-attachments/assets/5e17af1a-9d9a-4fa7-8a4a-719e201648aa" />

**Cloudflared config:**

```yaml
external_hostname: homeassistant.mydomain.com
additional_hosts:
  - hostname: paperless.mydomain.com
    service: http://55eca821-paperless-ngx:8099

```

**paperless-ngx config:**

```yaml
filename: "{created_year}/{correspondent}/{title}"
language: deu
language_packages: eng deu
default_superuser:
  username: REDACTED
  email: REDACTED
  password: REDACTED
timezone: UTC
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
ingress_auth: false
csrf_allowed: []
url: https://paperless.mydomain.com
```

Any help is much appreciated!

**Comment by BenoitAnastay** [comment]
Try with this port, you are using ingress dedicated port, that's why it's blocked.

```yaml
external_hostname: homeassistant.mydomain.com
additional_hosts:
  - hostname: paperless.mydomain.com
    service: http://55eca821-paperless-ngx:8000
```
